version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: nest_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: apipassword
      MYSQL_DATABASE: api-project
      MYSQL_USER: api-user
      MYSQL_PASSWORD: apipassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
